# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crumbproof', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='user_id',
        ),
    ]
