# config
:local = http://127.0.0.1:2500
:prod = https://flour.crumbproof.com

:localToken = 7d63fb3c8e4fa4fdd573e2db21b21891c0f2480b
:prodToken = c880d422b641b8d9a2de3570248f1d6787a806a0

:host = :local
:token = :localToken


:auth = Authorization: Token :token
:json = Content-Type: application/json



:headers = <<
:auth
:json

#

# Login

POST :host/rest-auth/login/
Content-Type: application/json

{ "password" : "password123"
, "username" : "user1"
}

### Response
  {
    "key": "7e5efc3b11ac5783d2fe2ebe8989c94312c36ce9"
  }

# Register
:user = user1

POST :host/rest-auth/registration/
Content-Type: application/json

{ "password1" : "password123"
, "password2" : "password123"
, "username" : ":user"
}

# Email is optional

### Response
  {
    "key": "7e5efc3b11ac5783d2fe2ebe8989c94312c36ce9"
  }


# List users

GET :host/users/
:headers

### Response
  # HTTP/1.0 200 OK
  {
    "count": 3,
    "next": null,
    "previous": null,
    "results": [
      {
        "url": "http://127.0.0.1:8000/users/3/",
        "username": "user2",
        "email": "user2@test.com",
        "groups": []
      },
      ...
    ]
  }


# List recipes
GET :host/recipes/
:headers

# Recipe Detail

:recipeId = 5

GET :host/recipes/:recipeId/
:headers

# New Recipe
#  - Must be authenticated

POST :host/recipes/
:headers

{
  "diff" : null,
  "base_recipe": null,
  "parent": null,
  "data" : {
    "name": "It was the only flour they had",
    "bake_time": 40,
    "oven_temperature": 250,
    "yield_count": 1,
    "yield_type": "Loaf",
    "ingredients": [
      {
        "name": "Lauke Wholegrain Breadmix",
        "quantity": 590,
        "unit": "grams"
      },
      {
        "name": "Water",
        "quantity": 360,
        "unit": "mL"
      },
      {
        "name": "Yeast",
        "quantity": 3,
        "unit": "Teaspoons"
      }
    ],
    "instructions": [
      {
        "content": "Dump all ingredients into the bowl",
        "time_gap_to_next": 0,
        "step_number": 1
      },
      {
        "content": "Mix everything together",
        "time_gap_to_next": 5,
        "step_number": 2
      },
      {
        "content": "Knead",
        "time_gap_to_next": 15,
        "step_number": 3
      },
      {
        "content": "Place into a cling wrapped container",
        "step_number": 4
      },
      {
        "content": "Proof",
        "time_gap_to_next": 30,
        "step_number": 5
      },
      {
        "content": "Fold",
        "step_number": 6
      },
      {
        "content": "Proof",
        "time_gap_to_next": 30,
        "step_number": 7
      },
      {
        "content": "Fold",
        "time_gap_to_next": 0,
        "step_number": 8
      },
      {
        "content": "Proof",
        "time_gap_to_next": 60,
        "step_number": 9
      },
      {
        "content": "Preheat oven and dutch oven",
        "step_number": 10
      },
      {
        "content": "Shape dough",
        "step_number": 11
      },
      {
        "content": "Final proof",
        "time_gap_to_next": 25,
        "step_number": 12
      },
      {
        "time_gap_to_next": 30,
        "content": "Start baking with lid on",
        "step_number": 13
      },
      {
        "content": "Remove lid and continue baking",
        "time_gap_to_next": 10,
        "step_number": 14
      },
      {
        "content": "Remove from oven and rest",
        "time_gap_to_next": 10,
        "step_number": 15
      },
      {
        "content": "EAT ALL THE BREAD",
        "step_number": 16
      }
    ]
    }
}
### Response
  # HTTP/1.0 201 Created
  {
    "url": "http://127.0.0.1:8000/recipes/2/",
    "name": "testRecipe",
    "bake_time": 20,
    "yield_count": 20,
    "yield_type": "Loaves",
    "user": "user2",
    "created": "2017-10-04T05:28:45.467884Z",
    "updated": "2017-10-04T05:28:45.467923Z",
    "deleted": null
  }

#
# Only the user that created the recipe can delete
:adminRecipe = 7
:recipeId = :adminRecipe

DELETE :host/recipes/:recipeId/
:auth

#

# Add recipe to user favourites
:recipeId = 5

POST :host/recipes/:recipeId/favourite/
:auth

#
:recipeId = 1

POST :host/recipes/:recipeId/unfavourite/
:auth

# Activities that are linked to this recipe, most recent first
:recipeId = 5

GET :host/recipes/:recipeId/activity_history/

  # Response (just a list of Activities)
  [
    {
      "id": 5,
      "name": "linked 2",
      "user": "user7",
      "recipe": 5,
      "recipe_name": "It was the only flour they had",
      "started": null,
      "created": "2017-10-21T08:50:37.960182Z",
      "completed": null,
      "oven_start": null,
      "oven_end": null,
      "crumb_shot": "https://crumbproof-img.s3.amazonaws.com/media/images/1096639b-5e3.jpg",
      "notes": null
    },
#


GET :host/ingredients/

# Activities
GET :host/activities/

    # Response
    {
      "count": 3,
      "next": null,
      "previous": null,
      "results": [
        {
          "id": 1,
          "name": "Crusty bread",
          "user": "user5",
          "recipe": null,
          "started": "2017-10-04T05:28:45.467884Z",
          "created": "2017-10-09T05:46:54.071279Z",
          "completed": "2017-10-04T05:28:45.467884Z",
          "oven_start": "2017-10-04T05:28:45.467884Z",
          "oven_end": "2017-10-04T05:28:45.467884Z"
        }
        ...

       ]
    }

#
:activityId = 1
GET :host/activities/:activityId

#
:recipeId = 5
GET :host/recipes/:recipeId/activities/

    # Response
    {
      "count": 31,
      "next": "http://127.0.0.1:2500/recipes/5/activities/?page=2",
      "previous": null,
      "recipe": "5",
      "results": [
        {
          "id": 32,
          "name": "Test bread",
          "user": "user1",
          "recipe": 5,
          "recipe_name": "It was the only flour they had",
          "started": "2017-10-04T05:28:45.467884Z",
          "created": "2017-10-24T05:33:02.639957Z",
          "completed": "2017-10-04T05:28:45.467884Z",
          "oven_start": "2017-10-04T05:28:45.467884Z",
          "oven_end": "2017-10-04T05:28:45.467884Z",
          "crumb_shot": "https://crumbproof-img.s3.amazonaws.com/media/images/51836251-db2.png",
          "notes": null
        },
        ....
      ]
    }

#
POST :host/activities/
:headers

{
  "name" : "Test bread",
  "recipe" : 5,
  "started": "2017-10-04T05:28:45.467884Z",
  "completed": "2017-10-04T05:28:45.467884Z",
  "oven_start": "2017-10-04T05:28:45.467884Z",
  "oven_end": "2017-10-04T05:28:45.467884Z",
  "crumb_shot": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
}

# Save web push subscription details for a logged in user
POST :host/user/web_push_subscription/$
:headers
{
  "endpoint": "https://fcm.googleapis.com/fcm/send/cuJuf4Z-qqM:APA91bGM0oz4W-yMbg6LVJT_ffZVrfEfh7t7YRk8bS4XrIn5QeZVxNC9mpsClgd0vgKUWdA3Y4jidPR9gUM-u-zGco354cj8S06_JTGLQgrD04QSSAcflKsQp_y82hA2F94dMq04BjN6",
  "expirationTime": null,
  "keys": {
    "p256dh": "BCKAOCaOkqwMmATzkiYUdEV3I9prEikQ3MWJ4mSYf6B9bmrePTneBI6b2jh_vRu4fRxiB7JRgA-wA4mQ_VOwbzU=",
    "auth": "YnYxWPuvwY8a1QXS1WGd3Q=="
  }
}


#

# TEST
GET :host/user_profiles/
:headers